### Todo: Adjust IP to your Docker Server IP 
### Step 1: List products
GET http://167.172.164.121:4000/products

### Step 2: Create a product
POST http://167.172.164.121:4000/products
Content-Type: application/json

{
  "name": "iMac Pro",
  "price": 4999
}

### Step 3: GET a product by id (ADJUST id from RESPONSE in Step 1) 
GET http://167.172.164.121:4000/products/6627be325e6c010012864861

### Update a product by id (ADJUST id fro RESPONSE in Step 2) 
PATCH  http://167.172.164.121:4000/products/6627be325e6c010012864861
Content-Type: application/json

{
  "price": 5999
}


### Delete a product by id (ADJUST id fro RESPONSE in Step 2) 
DELETE  http://167.172.164.121:4000/products/6627be325e6c010012864861

### 404 route Not Found
GET http://167.172.164.121:4000/abc_xyz

